microsoft/onnxruntime-inference-examples

.github/workflows/win-ci.yml, c_cxx/imagenet/image_loader_libjpeg.cc
Add c_cxx/imagenet to CI build pipeline and fix the build errors
=> Add c_cxx/imagenet to CI build pipeline and fix the build errors

mobile/examples/basic_usage/model/requirements.txt, mobile/examples/speech_recognition/model/requirements.txt
Always taking the latest ORT/ONNX may not work. Fix the versions here.
=> Fix onnxruntime/onnx versions in requirements.txt.

.gdn/.gdntsa, ci_build/azure_pipelines/compliance.yml, ci_build/policheck_exclusions.xml
=> Add a pipeline for compliance

quantization/nlp/bert/trt/e2e_tensorrt_bert_example.py
Update e2e script in order to use updated quantization tool to achieve better latency and accuracy.
=> Bert e2e example modification

.config/tsaoptions.json, .pipelines/OneBranch.Official.yml, .pipelines/OneBranch.PullRequest.yml
=> Add OneBranch config files

.config/tsaoptions.json
It missed some important options.  I wasn't able to verify it before I put it there.
=> Update tsaoptions.json file

c_cxx/squeezenet/CMakeLists.txt, c_cxx/squeezenet/README.md, c_cxx/squeezenet/main.cpp, c_cxx/squeezenet/run_capi_application.bat, c_cxx/squeezenet/run_capi_application.sh
This c-api application example will be used in the package pipeline to verify the pipelines artifact packages.
Please also see this PR https://github.com/microsoft/onnxruntime/pull/10794
=> Add another c++ simple example 

c_cxx/OpenVINO_EP/Linux/squeezenet_classification/README.md, c_cxx/OpenVINO_EP/Linux/squeezenet_classification/squeezenet_cpp_app.cpp, c_cxx/OpenVINO_EP/Linux/squeezenet_classification/squeezenet_cpp_app_io.cpp, c_cxx/OpenVINO_EP/Windows/README.md, c_cxx/OpenVINO_EP/Windows/squeezenet_classification/squeezenet_cpp_app.cpp, c_sharp/OpenVINO_EP/yolov3_object_detection/Program.cs, c_sharp/OpenVINO_EP/yolov3_object_detection/README.md
**Description:**
Updated README documents.
Updated csharp sample with latest ImageSharp API
Updated cpp samples with nchw changes
**Note:** The samples are now compatible with the latest openvino 2022.1 version.
=> OpenVINO-EP v4.0 samples update

mobile/examples/object_detection/ios/README.md
Fix link to ONNX to ORT format model conversion info.
See https://github.com/microsoft/onnxruntime/issues/11519
=> Fix link to ONNX to ORT format model conversion info.

c_cxx/Snpe_EP/README.md
update doc for Snpe EP to reflect the API change
=> update doc for Snpe EP to reflect the API change

c_sharp/Snpe_EP/vgg16_image_classification/image_classification.csproj
update snpe nuget version to 1.13.1
=> update snpe nuget version

mobile/examples/speech_recognition/model/requirements.txt
Update to a safer and newer torch version in sample requirements to solve the CG alert:
https://aiinfra.visualstudio.com/Lotus/_componentGovernance/97926/alert/8088465?typeId=13210915&pipelinesTrackingFilter=0
=> Update torch version in sample requirements.txt

quantization/nlp/bert/trt/e2e_tensorrt_bert_example.py
OpTypesToExcludeOutputQuantizatioin should be OpTypesToExcludeOutputQuantization
=> Fix option name in QDQQuantizer

js/README.md, js/api-usage-tensor-image/README.md, js/api-usage-tensor-image/index.html
Added a short example showing the use of Image <--> Tensor utility functions.
=> Added an example for using Image <--> Tensor conversion API

mobile/examples/super_resolution/android/app/src/main/java/ai/onnxruntime/example/superresolution/MainActivity.kt, mobile/examples/super_resolution/android/app/src/main/java/ai/onnxruntime/example/superresolution/SuperResPerformer.kt
- Changes to avoid session creation happening with every instance instantiation.
- Other minor changes
=> [Mobile SuperRes] Update ort session creation to app onCreate() stage

.github/workflows/gradle-wrapper-validation.yml, mobile/examples/super_resolution/android/gradle/wrapper/gradle-wrapper.properties
- Add github action to validate gradle-wrapper.jar checksums
- Add checksum for super_resolution gradle wrapper distribution
=> Gradle wrapper security updates

c_cxx/QNN_EP/mobilenetv2_classification/CMakeLists.txt, c_cxx/QNN_EP/mobilenetv2_classification/README.md, c_cxx/QNN_EP/mobilenetv2_classification/main.cpp, c_cxx/QNN_EP/mobilenetv2_classification/run_qnn_ep_sample.bat
Support from source or binary drop @HectorSVC @jywu-msft
=> Sample is more robust with checking/installing deps and common issues 

mobile/examples/object_detection/android/README.md, mobile/examples/object_detection/android/app/build.gradle, mobile/examples/speech_recognition/android/app/build.gradle, mobile/examples/speech_recognition/android/app/libs/readme.md, mobile/examples/speech_recognition/android/settings.gradle
Remove checked in pre-release `.aar` files and use the released ones instead.
=> Update Android samples to use released ORT packages

quantization/language_model/llama/main.py
Updated the LLama quantization example to use correct import.
=> fix llama example evaluate import issue

c_cxx/squeezenet/run_capi_application.bat
=> Use msbuild abs path

quantization/language_model/evaluation/README.md, quantization/language_model/evaluation/main.py, quantization/language_model/evaluation/ort_lm.py
Added performance script to the ORT Causal LLM evaluation example for testing accuracy and performance.
=> Adding perf to ORT LLM evaluation example

quantization/language_model/llama/README.md
The parameter of export cmd should be causal-lm-with-past
https://huggingface.co/docs/optimum/exporters/onnx/usage_guides/export_a_model
=> Fix llama README

.pipelines/OneBranch.Official.yml
This is to revert an accidental change in #251 .
=> Update OneBranch.Official.yml for Azure Pipelines

mobile/examples/super_resolution/ios/README.md
There's no Podfile under `../ios`.
=> Fix minor typo in `pod install` path

js/README.md, js/api-usage_ort-env-flags/README.md, js/api-usage_session-options/README.md, js/importing_onnxruntime-node/README.md, js/importing_onnxruntime-react-native/README.md, js/importing_onnxruntime-web/README.md, js/quick-start_onnxruntime-web-bundler/main.js, js/quick-start_onnxruntime-web-script-tag/index_esm.html
=> [web] add doc for importing and webgpu config/flags

mobile/examples/React_Native/ort-rn-basic-usage/App.tsx, mobile/examples/question_answering/android/app/src/main/java/ai/onnxruntime/example/question_answering/MainActivity.kt
=> [Mobile/React_Native] Fix the model input rank used in the expo app

mobile/examples/React_Native/ort-rn-basic-usage/README.md
=> Update readme doc for basic usage react native app to add extensions usage instructions.

python/models/llama2/LLaMA-2 E2E Notebook.ipynb
This PR fixes the CUDA version specified in the LLaMA-2 notebook.
=> Fix CUDA version in LLaMA notebook

python/OpenVINO_EP/tiny_yolo_v2_object_detection/requirements.txt, python/OpenVINO_EP/yolov4_object_detection/requirements.txt, python/OpenVINO_EP/yolov8_object_detection/README.md, python/OpenVINO_EP/yolov8_object_detection/colab_notebook/OVEP_yolov8_colab_sample.ipynb, python/OpenVINO_EP/yolov8_object_detection/requirements.txt, python/OpenVINO_EP/yolov8_object_detection/yolov8.py
This PR  involves object detection sample using yolov8 model, which uses the OpenVINO™ Execution Provider(OVEP) to run inference on Intel hardware devices and perform object detection to detect up to 80 different objects.
=> yolov8 object detection python sample

python/models/mistral/README.md, python/models/mistral/aml_submit_mistral_inference.py, python/models/mistral/environment/Dockerfile, python/models/mistral/inference-code/inference_setup.sh, python/models/mistral/ws_config_template.json
=> add mistral example

c_cxx/QNN_EP/mobilenetv2_classification/main.cpp, c_cxx/QNN_EP/mobilenetv2_classification/run_qnn_ep_sample.bat
1. Update the model path to reflect the Onnx model zoo changes. Models were moved to archive folder
2. Remove codes not used
=> update the model path to reflect Onnx model zoo changes

c_cxx/squeezenet/run_capi_application.bat, c_cxx/squeezenet/run_capi_application.sh
Update run_capi_application.sh: allow using a local model file
=> Update run_capi_application.sh: allow using a local model file

c_cxx/QNN_EP/mobilenetv2_classification/run_qnn_ep_sample.bat
Update model path due to Onnx model zoo changes
=> Update model path due to Onnx model zoo changes

c_cxx/QNN_EP/mobilenetv2_classification/mobilenetv2_helper.py, c_cxx/QNN_EP/mobilenetv2_classification/run_qnn_ep_sample.bat
use get_qnn_qdq_config to generate QDQ model for QNN EP
=> use get_qnn_qdq_config to generate QDQ model for QNN EP

c_cxx/customop/CMakeLists.txt, c_cxx/customop/README.md, c_cxx/customop/example.cc, c_cxx/customop/kernelone.py
Add one simple customop and run inference with it in C++
=> Add a simple custom op example in C++

python/models/llama/README.md
This PR fixes a format issue with the README.md file in the LLaMA-2 folder.
With this fix, the README tables display correctly now.
=> Update LLaMA README

quantization/image_classification/migraphx/resnet50/e2e_migraphx_resnet_example.py
- Added support for fp32 mode
- Fixed an issue during JSOn dump where `values.range_value` couldn't be converetd to json
- Fixed a possible issue during evaluation, where the result batch size doesn't match the with the expected
=> Update MIGraphX resnet50 example

mobile/examples/whisper/azure/android/app/build.gradle
Fix build. It doesn't work with the latest onnxruntime-extensions-android version.
=> Use ort-extensions version 0.11.0 in whisper/azure/android example.

c_cxx/OpenVINO_EP/Linux/squeezenet_classification/README.md, c_cxx/OpenVINO_EP/Windows/README.md, c_sharp/OpenVINO_EP/yolov3_object_detection/README.md, python/OpenVINO_EP/tiny_yolo_v2_object_detection/README.md, python/OpenVINO_EP/yolov4_object_detection/README.md
fixed broken links for OVEP-readme documentation.
=> fix broken links to models
