microsoft/onnxruntime-inference-examples

js/quick-start_onnxruntime-web-bundler/README.md, js/quick-start_onnxruntime-web-bundler/index.html, js/quick-start_onnxruntime-web-bundler/package.json, js/quick-start_onnxruntime-web-bundler/webpack.config.js
This change revise example onnxruntime-web-bundler: add webpack plugin to copy .wasm files
helps to resolve #4
=> [js] revise examples for onnxruntime-web-bundler

.gitignore, README.md, mobile/README.md, mobile/examples/image_classifications/android/README.md, mobile/examples/image_classifications/android/app/build.gradle, mobile/examples/image_classifications/android/app/src/main/java/ai/onnxruntime/example/imageclassifier/MainActivity.kt, mobile/examples/image_classifications/android/app/src/main/java/ai/onnxruntime/example/imageclassifier/ORTAnalyzer.kt, mobile/examples/image_classifications/android/app/src/main/res/raw/.gitignore, mobile/examples/image_classifications/android/build.gradle
Update mobile example to reflect the latest changes in the ORT Mobile
- Added the link to the jupyter notebook (PyTorch -> ONNX -> Quantization -> Convert to ORT), the notebook still need some pending updates (add convert to ORT, https://github.com/microsoft/onnxruntime/pull/7941)
- Used ORT mobile package from maven central, remove custom build part of the example
- Reorganized the Readme
- Minor updates to the App
=> Update ORT Mobile example [Android Image Classifier]

README.md, ci_build/azure_pipelines/mobile-examples-pipeline.yml, mobile/examples/basic_usage/ios/OrtBasicUsage.xcodeproj/project.pbxproj, mobile/examples/basic_usage/ios/OrtBasicUsageTests/Info.plist, mobile/examples/basic_usage/ios/OrtBasicUsageTests/OrtBasicUsageTests.swift, mobile/examples/basic_usage/ios/Podfile
Adding an initial CI build. Currently the OrtBasicUsage iOS example is tested.
Test build: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=427258&view=results
=> Add initial CI build

README.md
Moved the CI build definition. This change updates the URLs in the readme accordingly.
=> [Mobile CI] Update build badge URLs.

mobile/README.md, mobile/examples/object_detection/ios/ORTObjectDetection/ModelHandler.swift, mobile/examples/object_detection/ios/ORTObjectDetection/Storyboards/Main.storyboard, mobile/examples/object_detection/ios/ORTObjectDetection/ViewController.swift, mobile/examples/object_detection/ios/README.md
- Move `create ORTSession` to init() to avoid new sessions created for each run which can cause bad performance.
- Fix some typos in sample Readme file.
=> [iOS Object Detection] Move `create ORTSession` to init()

README.md
1. The old one for Mobile examples is not visible from public. The new one is.   I moved the build pipeline.
2. Add badges for the new pipelines.
=> Update Pipeline Status Badge in Readme.md

quantization/nlp/bert/trt/README.md
Add README for users to better understand and use our e2e BERT QDQ example.
=> Add README for BERT E2E example

python/OpenVINO_EP/yolov4_object_detection/README.md, python/OpenVINO_EP/yolov4_object_detection/yolov4.py, python/README.md
The ONNXRT Session API for python need to be updated for ONNXRT versions >= v1.9.0.
The EP has to explicitly mentioned and registered while loading the ONNX model using the session API.
=> [OpenVINO EP] Update Python Yolov4 sample

c_cxx/squeezenet/CMakeLists.txt, c_cxx/squeezenet/run_capi_application.bat, c_cxx/squeezenet/run_capi_application.sh
This PR is an update for the previous PR https://github.com/microsoft/onnxruntime-inference-examples/pull/87, due to some changes from Azure Pipelines, therefore this example folder needs to be updated as well.
=> Add another c++ simple example (Updated)

.pipelines/OneBranch.PullRequest.yml, c_cxx/CMakeLists.txt, c_cxx/squeezenet/CMakeLists.txt, c_cxx/squeezenet/main.cpp
1. Add the squeezenet example to CI build
2. Validate all C/C++ examples with the latest onnxruntime nightly build. (Something is better than nothing)
=> Add squeezenet to CI build

mobile/examples/basic_usage/model/requirements.txt, mobile/examples/object_detection/ios/ORTObjectDetection/prepare_model.requirements.txt
ONNX 1.10 does not restrict the maximum version of its protobuf dependency and it doesn't work with the latest. Pin the protobuf version in the requirements files here.
=> Pin protobuf dependency (of ONNX) to specific version.

mobile/examples/Maui/MauiVisionSample/MauiVisionSample/MauiVisionSample.csproj
Add short term workaround to issue with iOS publish where the CoreML frameworks is not added to the link list. Pending real fix from MAUI folks.
Also update ORT to 1.12.1 which has a better Android build.
=> Work around MAUI iOS publish issue

quantization/image_classification/cpu/resnet50_data_reader.py, quantization/image_classification/cpu/run.py
In ResNet50DataReader, it uses an onnx session to obtain the model input shape. However it passes a madeup model name to the onnx session, resulting in file not found error.
This change provide the original float model path to the data reader
=> Quantization tool example bug fix

quantization/image_classification/cpu/ReadMe.md, quantization/image_classification/cpu/ReadMe.txt, quantization/image_classification/cpu/resnet50_data_reader.py, quantization/image_classification/cpu/run.py, quantization/image_classification/cpu/run_qdq_debug.py
Adding example run_qdq_debug.py
=> add qdq debugging example

quantization/image_classification/cpu/ReadMe.md, quantization/language_model/gpt2/ReadMe.md, quantization/language_model/gpt2/data_utils.py, quantization/language_model/gpt2/generate_inputs.py, quantization/language_model/gpt2/gpt2_input_reader.py, quantization/language_model/gpt2/run_qdq.py, quantization/language_model/gpt2/run_qdq_debug.py
1. Adding quantization example for gpt-2 medium
2. Modify preprocessing module name
=> Adding quantization example for gpt-2 medium

c_cxx/MNIST/MNIST.cpp, c_cxx/README.md, c_cxx/imagenet/CMakeLists.txt, c_cxx/imagenet/image_loader.h, c_cxx/imagenet/local_filesystem.h, c_cxx/imagenet/main.cc, c_cxx/imagenet/sync_api.h, c_cxx/imagenet/sync_api_win.cc, c_cxx/squeezenet/main.cpp
`GetInputName/GetOutputName` has been deprected last release and now removed.
=> Remove deprecated API usage

mobile/examples/object_detection/ios/ORTObjectDetection/prepare_model.requirements.txt
"tensorflow 2.9.3 depends on protobuf<3.20 and >=3.9.2"
Picked a version less than 3.20.
=> Update protobuf version to be compatible with tensorflow requirement.

ci_build/azure_pipelines/mobile-examples-pipeline.yml, mobile/examples/super_resolution/ios/ORTSuperResolution/ORTSuperResolution.xcodeproj/project.pbxproj, mobile/examples/super_resolution/ios/ORTSuperResolution/ORTSuperResolution.xcodeproj/xcshareddata/xcschemes/ORTSuperResolution.xcscheme, mobile/examples/super_resolution/ios/ORTSuperResolution/ORTSuperResolution.xcodeproj/xcshareddata/xcschemes/ORTSuperResolutionTests.xcscheme, mobile/examples/super_resolution/ios/ORTSuperResolution/ORTSuperResolutionTests/ORTSuperResolutionTests.swift
- Add super res android example to mobile examples ci pipeline
- Add test configuration to the super res ios xcodeproj and added commands to run in ci pipeline.
Can update to Testing with Full/Mobile packages as the other samples in the future, start with testing with the existing pre-release version pods for ios and checked-in aar package for android.
=> Add super resolution example to mobile examples ci pipeline

mobile/examples/basic_usage/model/requirements.txt, mobile/examples/speech_recognition/model/requirements.txt
Update ONNX to 1.13 due to security warning.
> Versions of the package onnx before 1.13.0 are vulnerable to Directory Traversal as the external_data field of the tensor proto can have a path to the file which is outside the model current directory or user-provided directory, for example "../../../etc/passwd"
Also update transformers to newer version that supports python 3.10. The existing version triggers and attempt to build the tokenizers python package dependency from source which requires the Rust compiler. Model generation was successful with the new version.
=> Update ONNX to 1.13 due to security warning.

quantization/image_classification/cpu/ReadMe.md
resnet50-v1-13.onnx has ir_version 3 with opset 13. Causing trouble with onnx shape inference.
=> Remove corrupted example model

ci_build/azure_pipelines/mobile-examples-pipeline.yml, ci_build/azure_pipelines/templates/xcode-build-and-test-step.yml
The mobile examples CI build started failing recently and upgrading to a newer Xcode seems to fix it.
=> Update mobile examples CI build Xcode version to 14.2.

.github/workflows/windows.yml, c_cxx/CMakeLists.txt, c_cxx/fns_candy_style_transfer/image_file_wic.cc, c_cxx/imagenet/image_loader.cc, c_cxx/imagenet/image_loader_wic.cc, c_cxx/model-explorer/CMakeLists.txt, c_cxx/model-explorer/model-explorer.cpp
Compare to the ADO pipelines we already have, this one can directly publish scan results to Github website for view. It will be better integrated with Github UI. 
Example output:
=> Add a VC++ static analysis Github workflow

mobile/examples/object_detection/android/app/src/main/java/ai/onnxruntime/example/objectdetection/MainActivity.kt
When checked out on Linux the classes.txt assets file only has \n as line endings so that is how it gets packaged into the app. This change makes the splitting of that file work with such line endings too otherwise there will be a single long classification label instead of 80.
=> Object detection: work with Unix line endings in classes.txt file.

c_cxx/squeezenet/run_capi_application.bat
It's used in onnxruntime nuget pipeline.
Ort repo doesn't support VS2019 any more.
=> use vs 2022

quantization/language_model/evaluation/README.md, quantization/language_model/evaluation/main.py, quantization/language_model/evaluation/ort_lm.py, quantization/language_model/evaluation/requirements.txt
Adding accuracy evaluation example for evaluating ORT causal LLMs using the Eleuther AI Language Model Evaluation Harness.
Please be aware that when preparing the environment, there is no requirement to clone the lm-evaluation-harness repository for evaluation purposes.
=> Add accuracy evaluation example

python/models/llama_e2e.ipynb
This PR adds a Jupyter notebook to show an end-to-end inference example for [Meta's LLaMA-2](https://blogs.microsoft.com/blog/2023/07/18/microsoft-and-meta-expand-their-ai-partnership-with-llama-2-on-azure-and-windows/) with ONNX Runtime.
=> Add LLaMA E2E notebook

python/models/llama_e2e.ipynb
This PR adds a link to the already exported + optimized ONNX models in the [Microsoft repository](https://github.com/microsoft/Llama-2-Onnx/tree/main-CUDA_CPU).
=> Update LLaMA E2E notebook

c_cxx/squeezenet/run_capi_application.bat
The URL isn't available now.
Use local model like the .sh script to fix Nuget pipeline exception.
=> Use local models

js/api-usage-tensor-image/index.html
The line 68  is unnecessary as it is not being used anywhere in the main() function.
=> remove unnecessary line

c_cxx/QNN_EP/mobilenetv2_classification/main.cpp, c_cxx/QNN_EP/mobilenetv2_classification/run_qnn_ep_sample.bat
Update according to Ort PR https://github.com/microsoft/onnxruntime/pull/20107
The wrapper Onnx model generated from native QNN context binary already have Q, DQ nodes if the inputs/outputs are quantized data. So the example application doesn't need to quantize inputs and dequantize the outputs any more.
=> Remove Q & DQ since Onnx wrapper model has them already

c_cxx/accuracy_tool/CMakeLists.txt, c_cxx/accuracy_tool/README.md, c_cxx/accuracy_tool/build.bat
Updates build and README with relevant changes for ONNX Runtime 1.18.0. Notably, the ORT QNN NuGet package now includes the QNN SDK dlls.
=> [Accuracy tool] Update build and README with relevant changes for ONNX Runtime 1.18.0

mobile/examples/phi-3/android/app/src/main/java/ai/onnxruntime/genai/demo/MainActivity.java
In the original code there are two parallel lists. The bug is that tokenizer.model and tokenizer.json are out of order between the two lists. 
It would be easy enough to simply swap the ordering in the fileNames list, but it seems a bit more robust to simply have one list, so that this sort of thing would be harder to do.
=> Fix corrupted files issue in android Phi-3 demo

ci_build/azure_pipelines/mobile-examples-pipeline.yml, ci_build/azure_pipelines/templates/run-with-android-emulator-steps.yml, ci_build/azure_pipelines/templates/update-podfile-step.yml, ci_build/azure_pipelines/templates/use-jdk-step.yml, ci_build/azure_pipelines/templates/use-python-step.yml, ci_build/python/run_android_emulator.py, ci_build/python/util/android/android.py, ci_build/python/util/logger.py, ci_build/python/util/platform_helpers.py, ci_build/python/util/run.py, mobile/examples/basic_usage/ios/Podfile, mobile/examples/object_detection/ios/ORTObjectDetection/prepare_model.sh, mobile/examples/object_detection/ios/Podfile, mobile/examples/question_answering/ios/ORTQuestionAnswering/Podfile, mobile/examples/speech_recognition/ios/Podfile, mobile/examples/super_resolution/ios/ORTSuperResolution/Podfile
Fix the mobile examples CI pipeline.
In particular:
- Move Android examples to run on Linux build agents
- Copy over Android emulator helper scripts from ORT at commit 5e66fcc703
- Fix model download script for iOS object detection example
- Update Podfiles to use iOS 13 as that is the new minimum version required by ORT
- Refactor CI pipeline
=> Fix mobile examples CI pipeline

mobile/examples/speech_recognition/model/requirements.txt, mobile/examples/speech_recognition/model/wav2vec2_gen.py
See https://github.com/microsoft/onnxruntime-inference-examples/pull/478.
Bumping the torch dependency requires some other updates. This PR updates more of them.
=> Update mobile/examples/speech_recognition/model dependencies.

ci_build/azure_pipelines/mobile-examples-pipeline.yml, ci_build/azure_pipelines/templates/xcode-build-and-test-step.yml
Updating because the macOS-12 image is deprecated.
=> Update macOS image version, Xcode version, and simulator target for mobile example CI pipeline

ci_build/azure_pipelines/templates/xcode-build-and-test-step.yml
Specify iOS simulator version in CI build. Ensure it is compatible with the version of Xcode that is used.
=> Specify iOS simulator version.
